// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	"context"

	"github.com/stretchr/testify/mock"
)

// IPushNotificationGateway is an autogenerated mock type for the IPushNotificationGateway type
type IPushNotificationGateway struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, token, title, body, data
func (_m *IPushNotificationGateway) Send(ctx context.Context, token, title, body string, data map[string]string) (string, error) {
	ret := _m.Called(ctx, token, title, body, data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string) (string, error)); ok {
		return rf(ctx, token, title, body, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string) string); ok {
		r0 = rf(ctx, token, title, body, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, map[string]string) error); ok {
		r1 = rf(ctx, token, title, body, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPushNotificationGateway creates a new instance of IPushNotificationGateway.
func NewIPushNotificationGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPushNotificationGateway {
	m := &IPushNotificationGateway{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
